name: echo
description: "A modern API client built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.3

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # UI & Window Management
  window_manager: ^0.3.9
  flutter_acrylic: ^1.1.4
  google_fonts: ^6.2.1
  multi_split_view: ^2.2.0
  code_text_field: ^1.1.0

  # Utilities
  path_provider: ^2.1.2
  uuid: ^4.4.0
  file_saver: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generators
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
